-- Generated with IA

INSERT INTO category (name) VALUES ('Injectables');
INSERT INTO category (name) VALUES ('Peels');
INSERT INTO category (name) VALUES ('Fat Dissolving ');
INSERT INTO category (name) VALUES ('Sclerotherapy');
INSERT INTO category (name) VALUES ('Threads');
INSERT INTO category (name) VALUES ('Weightloss');
INSERT INTO category (name) VALUES ('IV Therapy');
INSERT INTO category (name) VALUES ('Vitamin Injections');
INSERT INTO category (name) VALUES ('Peptide Therapy');
INSERT INTO category (name) VALUES ('Ultrasound');
INSERT INTO category (name) VALUES ('Facials');
INSERT INTO category (name) VALUES ('Other Non Medical');
INSERT INTO category (name) VALUES ('Consultation');
INSERT INTO category (name) VALUES ('Follow up');
INSERT INTO category (name) VALUES ('Other');
INSERT INTO service (name, description, category_id) VALUES ('Neuromodulator', 'Neuromodulator description', 1);
INSERT INTO service (name, description, category_id) VALUES ('HA Dermal Filler', 'HA Dermal Filler description', 1);
INSERT INTO service (name, description, category_id) VALUES ('Calcium Hydroxyapatite', 'Calcium Hydroxyapatite description', 1);
INSERT INTO service (name, description, category_id) VALUES ('Hyaluronidase', 'Hyaluronidase description', 1);
INSERT INTO service (name, description, category_id) VALUES ('Polymethyl methacrylate (PMMA)', 'Polymethyl methacrylate (PMMA) description', 1);
INSERT INTO service (name, description, category_id) VALUES ('Poly-L Lactic Acid', 'Poly-L Lactic Acid description', 1);
INSERT INTO service (name, description, category_id) VALUES ('Chemical Peel', 'Chemical Peel description', 2);
INSERT INTO service (name, description, category_id) VALUES ('Deoxycholic Acid', 'Deoxycholic Acid description', 3);
INSERT INTO service (name, description, category_id) VALUES ('Sclerotherapy', 'Sclerotherapy description', 4);
INSERT INTO service (name, description, category_id) VALUES ('PDO Threads', 'PDO Threads description', 5);
INSERT INTO service (name, description, category_id) VALUES ('GLP-1 Antagonists', 'GLP-1 Antagonists description', 6);
INSERT INTO service (name, description, category_id) VALUES ('IV Therapy', 'IV Therapy description', 7);
INSERT INTO service (name, description, category_id) VALUES ('Vitamin Injections', 'Vitamin Injections description', 8);
INSERT INTO service (name, description, category_id) VALUES ('Peptide Therapy', 'Peptide Therapy description', 9);
INSERT INTO service (name, description, category_id) VALUES ('Ultrasound', 'Ultrasound description', 10);
INSERT INTO service (name, description, category_id) VALUES ('Hydrafacial', 'Hydrafacial description', 11);
INSERT INTO service (name, description, category_id) VALUES ('SilkPeel', 'SilkPeel description', 11);
INSERT INTO service (name, description, category_id) VALUES ('Diamond Glow', 'Diamond Glow description', 11);
INSERT INTO service (name, description, category_id) VALUES ('Other facial', 'Other facial description', 11);
INSERT INTO service (name, description, category_id) VALUES ('Massage', 'Massage description', 12);
INSERT INTO service (name, description, category_id) VALUES ('Microblading', 'Microblading description', 12);
INSERT INTO service (name, description, category_id) VALUES ('Microdermabrasion', 'Microdermabrasion description', 12);
INSERT INTO service (name, description, category_id) VALUES ('Dermaplaning', 'Dermaplaning description', 12);
INSERT INTO service (name, description, category_id) VALUES ('Teeth Whitening', 'Teeth Whitening description', 12);
INSERT INTO service (name, description, category_id) VALUES ('Waxing', 'Waxing description', 12);
INSERT INTO service (name, description, category_id) VALUES ('Other Non Medical Service', 'Other Non Medical Service description', 12);
INSERT INTO service (name, description, category_id) VALUES ('Consultation', 'Consultation description', 13);
INSERT INTO service (name, description, category_id) VALUES ('Follow up', 'Follow up description', 14);
INSERT INTO service (name, description, category_id) VALUES ('Other', 'Other description', 15);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Botox', 1.12, 'Allergan', 1);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Daxxify', 1.16, 'Revance', 1);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Dysport', 1.05, 'Galderma', 1);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Jeuveau', 1.49, 'Evolus', 1);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Xeomin', 1.25, 'Merz', 1);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Juvederm Ultra XC', 1.43, 'Allergan', 2);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Juvederm Ultra Plus XC', 1.25, 'Allergan', 2);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Juvederm Volbella', 1.2, 'Allergan', 2);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Juvederm Vollure', 1.22, 'Allergan', 2);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Juvederm Voluma', 1.1, 'Allergan', 2);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Juvederm Volux', 1.44, 'Allergan', 2);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Juvederm Skinvive', 1.03, 'Allergan', 2);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Restylane', 1.02, 'Galderma', 2);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Restylane-L', 1.2, 'Galderma', 2);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Restylane Contour', 1.24, 'Galderma', 2);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Restylane Defyne', 1.04, 'Galderma', 2);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Restylane Eyelight', 1.25, 'Galderma', 2);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Restylane Kysse', 1.02, 'Galderma', 2);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Restylane Lyft', 1.02, 'Galderma', 2);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Restylane Silk', 1.06, 'Galderma', 2);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Restylane Refyne', 1.47, 'Galderma', 2);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('RHA 2', 1.34, 'Revance', 2);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('RHA 3', 1.3, 'Revance', 2);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('RHA 4', 1.49, 'Revance', 2);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('RHA Redensity', 1.12, 'Revance', 2);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Revanesse Lips', 1.11, 'Prollenium', 2);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Revanesse Versa', 1.23, 'Prollenium', 2);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Belotero Balance', 1.42, 'Merz', 2);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Radiesse', 1.44, 'Merz', 3);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Hyperdilute Radiesse', 1.25, 'Merz', 3);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Hylanex', 1.39, NULL, 4);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Bellafill', 1.11, 'Suneva', 5);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Sculptra', 1.06, 'Galderma', 6);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('PRX', 1.31, 'WiQo', 7);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('VI Peel: Classic Precision Plus', 1.15, 'VI', 7);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('SkinMedica: Illuminze', 1.41, 'Allergan', 7);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('SkinMedica: Rejuvenize', 1.33, 'Allergan', 7);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('SkinMedica: Vitalize', 1.15, 'Allergan', 7);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('ZO Skin Health: 3 step peel', 1.47, 'Zo Skin Health', 7);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Perfect DermaPeel', 1.46, 'Bella Medical Products', 7);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('TCA', 1.24, NULL, 7);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Other Chemical Peel Product', 1.18, NULL, 7);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Kybella', 1.17, NULL, 8);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Asclera', 1.4, 'Asclera', 9);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Smooth PDO Threads', 1.35, 'Mint', 10);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Smooth PDO Threads', 1.03, 'Miracu', 10);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Smooth PDO Threads', 1.09, 'PDO Max', 10);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Smooth PDO Threads', 1.06, 'V Soft Lift', 10);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Smooth PDO Threads', 1.46, 'Viola Threads', 10);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Smooth PDO Threads', 1.14, 'NovaThreads', 10);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Smooth PDO Threads', 1.44, 'EuroThreads', 10);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Smooth PDO Threads', 1.43, 'Other', 10);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Lifting PDO Threads', 1.18, 'Mint', 10);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Lifting PDO Threads', 1.01, 'Miracu', 10);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Lifting PDO Threads', 1.26, 'PDO Max', 10);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Lifting PDO Threads', 1.39, 'V Soft Lift', 10);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Lifting PDO Threads', 1.15, 'Viola Threads', 10);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Lifting PDO Threads', 1.11, 'NovaThreads', 10);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Lifting PDO Threads', 1.09, 'EuroThreads', 10);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Lifting PDO Threads', 1.27, 'Other', 10);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Barbed/Cones PDO Threads', 1.11, 'Mint', 10);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Barbed/Cones PDO Threads', 1.32, 'Miracu', 10);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Barbed/Cones PDO Threads', 1.47, 'PDO Max', 10);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Barbed/Cones PDO Threads', 1.03, 'V Soft Lift', 10);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Barbed/Cones PDO Threads', 1.35, 'Viola Threads', 10);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Barbed/Cones PDO Threads', 1.28, 'NovaThreads', 10);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Barbed/Cones PDO Threads', 1.31, 'EuroThreads', 10);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Barbed/Cones PDO Threads', 1.41, 'Other', 10);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Trizepatide', 1.02, NULL, 11);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Phentermine', 1.45, NULL, 11);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Liraglutide', 1.18, NULL, 11);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Semaglutide', 1.1, NULL, 11);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('B Vitamins', 1.11, NULL, 12);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Vitamin C', 1.17, NULL, 12);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Arginine', 1.35, NULL, 12);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Ornithine', 1.16, NULL, 12);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Lysine', 1.34, NULL, 12);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Carnitine', 1.17, NULL, 12);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Ascorbic Acid', 1.15, NULL, 12);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Biotin', 1.39, NULL, 12);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Manganese', 1.13, NULL, 12);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Copper', 1.16, NULL, 12);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Magnesium Chloride', 1.36, NULL, 12);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Calcium Chloride', 1.13, NULL, 12);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('NAD', 1.04, NULL, 12);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Zinc', 1.25, NULL, 12);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Glutathione', 1.2, NULL, 12);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('B-12', 1.0, NULL, 13);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('MIC', 1.03, NULL, 13);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Glutathione', 1.17, NULL, 13);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('Ipamorelin', 1.15, NULL, 14);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('CJC', 1.12, NULL, 14);
INSERT INTO product (name, markup, supplier, service_id) VALUES ('BPC 157', 1.05, NULL, 14);
